name = "jazz"
version = "1.0.0"
description = "Practice material for improvisers, transposed for your horn"
licences = ["MIT"]
repository = { type = "github", user = "nerggnet", repo = "jazz" }
links = [{ title = "Try it", href = "https://nerggnet.github.io/jazz/" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.4.0 and < 3.0.0"
